### ISSUE TITLE
How to get custom shader operational in 2020.1.16f1?

### ISSUE THREAD

**Issue by JoshuaHeim** [Xentiie/SeamlessVoronoi#1]
Bringing this into a 2020.1.16f1 project throws the following errors in console:

Assets\Materials\Shaders\SeamlessVoronoi-master\Node\SeamlessVoronoi.cs(9,32): error CS0122: 'CodeFunctionNode' is inaccessible due to its protection level

Followed by 33 more errors to do with protection level. Is there a solution to get this working?

**Comment by Xentiie** [comment]
Check the hlsl code in the .cs file. You can copy-paste it in the new "Custom Node". You might need to modify it a little.

**Comment by Panicat** [comment]
Hello, it's not working for me. I tried copying the class, the whole script, or even just strings and such to a Code Function in shader graph. Tried in both URP and built in. What else do I need to do? Any update on this?
